-- MySQL Script generated by MySQL Workbench
-- Thu Jul 30 22:56:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventas_farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas_farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas_farmacia` DEFAULT CHARACTER SET utf8mb4 ;
USE `ventas_farmacia` ;

-- -----------------------------------------------------
-- Table `tbl_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `detalle` VARCHAR(70) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(5) NOT NULL,
  `n_documento` VARCHAR(11) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(9) NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `id_cargo` INT NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_cargo_idx` (`id_cargo` ASC),
  CONSTRAINT `fk_cargo`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `tbl_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `t_documento` VARCHAR(5) NOT NULL,
  `n_documento` VARCHAR(11) NOT NULL,
  `edad` INT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `est_civil` VARCHAR(10) NULL,
  `celular` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `id_categoria` INT NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `codigo` VARCHAR(9) NOT NULL,
  `precio` DOUBLE(11,2) NOT NULL,
  `imagen` VARCHAR(200) NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_categoria_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tbl_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `total` DOUBLE(11,2) NOT NULL,
  `est_entrega` VARCHAR(45) NOT NULL,
  `est_pago` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(15) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_ventas`),
  INDEX `fk_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tbl_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalle_ventas` (
  `id_detalleventas` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_ventas` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE(11,2) NOT NULL,
  `total` DOUBLE(11,2) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_detalleventas`),
  INDEX `fk_dv_producto_idx` (`id_producto` ASC),
  INDEX `fk_dv_ventas_idx` (`id_ventas` ASC),
  CONSTRAINT `fk_dv_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tbl_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dv_ventas`
    FOREIGN KEY (`id_ventas`)
    REFERENCES `tbl_ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_acceso_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_acceso_cliente` (
  `id_acceso_cliente` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_acceso_cliente`),
  INDEX `fk_acceso_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_acceso_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tbl_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_comprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_comprobantes` (
  `id_comprobante` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_ventas` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `t_comprobante` VARCHAR(15) NOT NULL,
  `serie_com` VARCHAR(7) NOT NULL,
  `nro_com` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_comprobante`),
  INDEX `fk_t_com_cliente_idx` (`id_cliente` ASC),
  INDEX `fk_t_com_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_t_com_ventas_idx` (`id_ventas` ASC),
  CONSTRAINT `fk_t_com_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tbl_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_com_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tbl_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_com_ventas`
    FOREIGN KEY (`id_ventas`)
    REFERENCES `tbl_ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
